### ISSUE TITLE
Multiple eslint-plugin package approach that may fix #8

### ISSUE THREAD

**Issue by Rel1cx** [eslint-react/eslint-react#10]
Continue on the https://github.com/eslint-react/eslint-react/tree/flat-config branch if we need to do this.

**Comment by Rel1cx** [comment]
@hyoban if we can not keep the same rule name format like `jsx/no-array-index-key` in FlatConfig, you can make PR in this approach to help with refactoring into multiple packages.

I'd really appreciate it.

**Comment by hyoban** [comment]
I began to think about replacing `
/` with `-`, but this affects our original intention for classification. It may be a better way to cut it into different packages. This is also beneficial for us to maintain the relevant rules.

**Comment by hyoban** [comment]
I'm very interested in this project. Can you invite me to join this team? I will try my best to do some work.

**Comment by Rel1cx** [comment]
> I'm very interested in this project. Can you invite me to join this team? I will try my best to do some work.

Sure, I'll send an invitation.

**Comment by Rel1cx** [comment]
> I began to think about replacing ` /` with `-`, but this affects our original intention for classification. It may be a better way to cut it into different packages. This is also beneficial for us to maintain the relevant rules.

agree.
