### ISSUE TITLE
`react/jsx-props-no-spreading` `··············->` `@eslint-react/jsx/no-spreading-props`

### ISSUE THREAD

**Issue by Rel1cx** [eslint-react/eslint-react#102]

**Comment by hyoban** [comment]
Regarding this rule, do we need the original option? My preference now is to make it completely non-configurable, emitting a warning at all times.

https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-props-no-spreading.md#rule-options

**Comment by Rel1cx** [comment]
> Regarding this rule, do we need the original option? My preference now is to make it completely non-configurable, emitting a warning at all times.
> 
> [jsx-eslint/eslint-plugin-react@`master`/docs/rules/jsx-props-no-spreading.md#rule-options](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-props-no-spreading.md?rgh-link-date=2023-11-10T05%3A06%3A57Z#rule-options)

True, no options, warning then don't put in recommended presets

**Comment by Rel1cx** [comment]
https://github.com/search?q=react%2Fjsx-props-no-spreading&type=code&p=1

In fact, after investigating the use of this rule in a production environment, I don't think we should migrate it now 😆.

**Comment by Rel1cx** [comment]
Closed it for now, reopen it if needed in the future.

**Comment by Rel1cx** [comment]
I've replaced this rule with a couple of rules, which aren't exactly equivalent but are more practical.
