### ISSUE TITLE
Can `no-leaked-conditional-rendering` support `React.ReactNode`?

### ISSUE THREAD

**Issue by hyoban** [eslint-react/eslint-react#112]
```tsx
type AppProps<T> = {
  someFunction: (data: T) => React.ReactNode;
};
function App<T>({ someFunction }: AppProps<T>) {
  return <>{!!someFunction && someFunction(1 as T)}</>;
}
```

**Comment by hyoban** [comment]
As an aside, I accidentally pushed a [commit](https://github.com/eslint-react/eslint-react/commit/041a36843b2cfb317aa9e8bf59ebe223f6462e06) directly to the main branch. I hope I didn’t break anything.

**Comment by Rel1cx** [comment]
> ```tsx
> type AppProps<T> = {
>   someFunction: (data: T) => React.ReactNode;
> };
> function App<T>({ someFunction }: AppProps<T>) {
>   return <>{!!someFunction && someFunction(1 as T)}</>;
> }
> ```

The code was added to the tests just now, no errors.

**Comment by Rel1cx** [comment]
> As an aside, I accidentally pushed a [commit](https://github.com/eslint-react/eslint-react/commit/041a36843b2cfb317aa9e8bf59ebe223f6462e06) directly to the main branch. I hope I didn’t break anything.

If you find a bug, it's best to raise an issue before submitting a PR, as it's possible I'm working on a fix.

**Comment by hyoban** [comment]
> > ```tsx
> > type AppProps<T> = {
> >   someFunction: (data: T) => React.ReactNode;
> > };
> > function App<T>({ someFunction }: AppProps<T>) {
> >   return <>{!!someFunction && someFunction(1 as T)}</>;
> > }
> > ```
> 
> The code was added to the tests just now, no errors.

This code does not work in version 0.8.1. It doesn't matter, it's fixed now.
