### ISSUE TITLE
Can you publish a new version to npm so that i can use it with eslint-define-config

### ISSUE THREAD

**Issue by hyoban** [eslint-react/eslint-react#41]
And maybe we also need something like [changelogithub](https://github.com/antfu/starter-ts/blob/main/.github/workflows/release.yml) with [bumpp](https://github.com/antfu/bumpp)

**Comment by Rel1cx** [comment]
ok.

**Comment by Rel1cx** [comment]
Ok, I will publish 0.5.4 to NPM.

**Comment by Rel1cx** [comment]
> And maybe we also need something like [changelogithub](https://github.com/antfu/starter-ts/blob/main/.github/workflows/release.yml?rgh-link-date=2023-10-28T07%3A24%3A28Z) with [bumpp](https://github.com/antfu/bumpp)

I'll do some research and see what I can use.

**Comment by Rel1cx** [comment]
Continue in #42.
