### ISSUE TITLE
Rule Request: implement `eslint-plugin-react` rules

### ISSUE THREAD

**Issue by SukkaW** [eslint-react/eslint-react#9]
- [x] `no-children-in-vold-dom-elements`: #12
- [ ] `jsx/no-unknown-property`: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-unknown-property.md
- [x] `jsx/enforce-component-name-pascal-case`: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-pascal-case.md
- [x] `naming-convention/filename-extension`: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-filename-extension.md
- [ ] `require-render-return`: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/require-render-return.md
- [ ] `ensure-class-component-method-order`: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/sort-comp.md
- [x] `ensure-style-prop-object`: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/style-prop-object.md
- [ ] `no-access-state-in-setstate`: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-access-state-in-setstate.md
- [x] `jsx/prefer-fragment-syntax`: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-fragments.md
- [x] `jsx/enforce-jsx-key`: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-key.md
- [x] `no-string-refs`
- [x] `jsx/no-useless-fragment`: #64 
- [ ] `no-unused-class-component-methods`: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-unused-class-component-methods.md
- [x] `no-missing-iframe-sandbox-attribute`: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/iframe-missing-sandbox.md
- [x] `no-object-type-as-default-prop`: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-object-type-as-default-prop.md
- [x] `require-button-has-type-attribute`: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/button-has-type.md
- [x] `no-namespace`: #13 

-----

- [ ] Add all rules implementation to `rules` exports
- [ ] Link all rules implementation documentation to README.md

-----

- [ ] `jsx/no-script-url`: Custom Component and prop support

**Comment by Rel1cx** [comment]
Will be added to the pending list.

**Comment by Rel1cx** [comment]
> > Will be added to the pending list.
> 
> @Rel1cx Let's just track them right here then. I will start port those rules when I get time.

`jsx/enforce-jsx-key` has been implemented by the three rules
- `jsx/no-missing-key`
- `jsx/no-duplicate-key`
- `jsx/no-array-index-key`
Except "before-spread", the implementation of these three rules can detect more problems than the original rules.
If necessary, we can also add a `jsx/ensure-key-before-spread`

**Comment by Rel1cx** [comment]
And `no-object-type-as-default-prop` already implemented and covered by [`no-unstable-default-props`](https://github.com/eslint-react/eslint-react/blob/main/packages/eslint-plugin/src/rules/no-unstable-default-props.ts)

**Comment by hyoban** [comment]
`naming-convention/filename-extension` already implemented by [`naming-convention/filename-extension`](https://github.com/eslint-react/eslint-react/blob/flat-config/packages/eslint-plugin-naming-convention/src/rules/filename-extension.ts)

**Comment by Rel1cx** [comment]
Since many rules has been changed, we track the migration status in #85.
